Changed Dockerfile base to dsci-100
UBC-MDS/prog-python-data-science-students pull request #2
Opened 2020-11-18 21:19 UTC by ecool50

2020-11-19 08:12 UTC, ttimbers commented
What are the `--dev-build=False --minimize=False` arguments for?

2020-11-19 08:38 UTC, hfboyce commented
> What are the `--dev-build=False` and `--minimize=False` arguments for?

Every time we try to build, it would timeout with `RuntimeError: JupyterLab failed to build`.

[This](`https://github.com/jupyterlab/jupyterlab/issues/7777 ) kinda explains a bit but over my understanding. After googling away without being able to build because it was timing out, several issues recommended these arguments to surpass this error. 

Also [here](https://pypi.org/project/jupyter-bokeh/) we found:
> On slow or limited memory systems, one can use --minimize=False to reduce compilation times or make Jupyter Lab build runtime bundles at all.

Essentially we are using them because if we don't, the build doesn't complete. 

We have checked that the container works, the assignments can be executed and the extensions used.

2020-11-19 18:24 UTC, ttimbers commented
Thanks for the explanation. Let's try to remove it and see if it builds on the runner since it did last time with these extensions and you haven't changed anything with the extensions. If it fails, we will add them back in.

2020-11-19 18:25 UTC, ttimbers requested changes

2020-11-19 18:25 UTC, ttimbers commented on dockerfiles/dsci-011/Dockerfile
> +RUN jupyter labextension install --dev-build=False --minimize=False jupyterlab-flake8 \
```suggestion
RUN jupyter labextension install jupyterlab-flake8 \
```

2020-11-19 18:25 UTC, ttimbers commented on dockerfiles/dsci-011/Dockerfile
> +    && jupyter labextension install --dev-build=False --minimize=False @ryantam626/jupyterlab_code_formatter \
```suggestion
    && jupyter labextension install @ryantam626/jupyterlab_code_formatter \
```

2020-11-19 18:25 UTC, ttimbers commented on dockerfiles/dsci-011/Dockerfile
> +    && jupyter lab build --minimize=False
```suggestion
    && jupyter lab build
```

2020-11-19 19:17 UTC, ttimbers commented
I removed this flag and was able to successfully build the image locally after I upped the Docker memory allocation to 4GB from 2GB under Docker preferences:

<img width="1038" alt="Screen Shot 2020-11-19 at 11 15 29 AM" src="https://user-images.githubusercontent.com/6865016/99712927-93cb6080-2a58-11eb-870c-188214a92719.png">

So I will now accept this PR and we can see if it builds successfully on the GitHubActions runner. Can you also try to build this version locally (without the  --dev-build=False and --minimize=False arguments) and test it again on the assignments? Just to be double sure?

2020-11-19 19:17 UTC, merged

2020-11-24 17:58 UTC, hfboyce commented
Hi! Sorry, I missed this. I just rebuilt and tested it on the assignments and we are ok on my end here!